### ISSUE TITLE
google adsense

### ISSUE THREAD

**Issue by averyrobbins1** [ertuil/erblog#18]
How would you add google adsense to the theme?

**Comment by ertuil** [comment]
I am sorry but I don't have a plan to support AdSence because it is not available in Mainland China (WHAT A PITY). However, it is easy to inject any codes in this theme, because hooks are left for you. You can put AdSence codes into `layouts/partials/self-define-head.html` or other hooks. [Hooks Docs](https://github.com/ertuil/erblog#4-user-defined-html-hooks).

If it doesn't fit your needs, it is free to fork this theme since it is under MIT License.
Thanks.

**Comment by averyrobbins1** [comment]
Okay that's no problem! Thank you. I will probably do as you suggested.
